### PR TITLE
Do not use Tycho in eclipse-cbi-plugin

### PR DESCRIPTION
**Pull request by laeubi**
Currently the plugin relies on some of Tycho components and classes this has the risk of breakage and incompatibility.

This do the following
- drop generate-api-build-xml mojo, if it is useful for anyone it should be migrated to Tycho
- remove Tycho dependency
- embed relevant portions of Tycho code that are actually used here

As a background, we are currently migrate Tycho to Maven 4 and therefore changing some internals to prepare for this step. This has suddenly break the mojo for unknown reasons see for example:

https://github.com/eclipse-tycho/tycho/actions/runs/10814711934/job/30001836975

```
Error:  Failed to execute goal org.eclipse.cbi.maven.plugins:eclipse-cbi-plugin:1.5.0:plugin-versions (plugin-versions) on project eclipse-junit-tests: Execution plugin-versions of goal org.eclipse.cbi.maven.plugins:eclipse-cbi-plugin:1.5.0:plugin-versions failed: Unable to load the mojo 'plugin-versions' (or one of its required components) from the plugin 'org.eclipse.cbi.maven.plugins:eclipse-cbi-plugin:1.5.0': java.util.NoSuchElementException
Error:        role: org.apache.maven.plugin.Mojo
Error:    roleHint: org.eclipse.cbi.maven.plugins:eclipse-cbi-plugin:1.5.0:plugin-versions
Error:  -> [Help 1]
```

### CODE REVIEW

**Comment by akurtakov** [comment]
I'm merging this one now as we have to keep progressing on Tycho/Platform side.

**Comment by akurtakov** [comment]
@laeubi Would you please switch platform build to used 1.5.1-SNAPSHOT? If/when this is proved to not cause issues we should ask @fredg02 / @mbarbero for a release.

**Comment by akurtakov** [comment]
@fredg02 @mbarbero Would you please release version 1.5.1 of cbi plugins? This is needed so Platform build doesn't use snapshot of cbi-plugin/jarsigner. The change to not require Tycho in org.eclipse.cbi.plugin is purely internal so no need for minor version bump IMO.

**Comment by mbarbero** [comment]
1.5.2 has been released (no 1.5.1 as there has been a quirk during release)

**Pull request merged**
