### PR TITLE
Do not submit: Test

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by akurtakov** [comment]
Thanks for guiding me one more time - https://github.com/eclipse-cbi/org.eclipse.cbi/commit/5807bb7f3b0e7e5d8a2d8bb7c245178c74cea098 !

**Comment by fredg02** [comment]
> Thanks for guiding me one more time - [5807bb7](https://github.com/eclipse-cbi/org.eclipse.cbi/commit/5807bb7f3b0e7e5d8a2d8bb7c245178c74cea098) !

No worries. It was a lucky shot after comparing the workflow file with https://github.com/eclipse-cdt/cdt-lsp/actions/runs/8000156547/workflow.

**Pull request closed without merging**
